# Example Prod Environment Setup

name: ls_prod

services:
    # Laravel App
    ls_prod_app:
        image: serversideup/php:8.2-fpm-nginx
        container_name: ls_prod_app
        stdin_open: true
        tty: true
        restart: always
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www/html
        environment:
            RUN_LARAVEL_AUTOMATIONS: 'false'
            AUTORUN_ENABLED: 'true'
            AUTORUN_LARAVEL_STORAGE_LINK: 'false'
            AUTORUN_LARAVEL_MIGRATION: 'true'
            SSL_MODE: 'off'
        networks:
            - app_net
            - redis_net
        command: ['su', 'webuser', '-c', 'php artisan schedule:work']

    # Database
    ls_prod_db:
        image: mysql:latest
        container_name: ls_prod_db
        restart: unless-stopped
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            ON_CREATE_DB: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - app_net

    # Redis
    ls_prod_redis:
        image: redis:alpine
        container_name: ls_prod_redis
        hostname: ls_prod_app
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - redis_net

networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.10.0.0/16

    redis_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.40.0.0/16
