# Example Dev Environment Setup

version: '3.8'

name: ls_dev

services:
    # Laravel App
    ls_dev_app:
        image: serversideup/php:8.2-fpm-nginx
        container_name: ls_dev_app
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www/html
        environment:
            RUN_LARAVEL_AUTOMATIONS: 'true'
            AUTORUN_ENABLED: 'true'
            AUTORUN_LARAVEL_STORAGE_LINK: 'true'
            AUTORUN_LARAVEL_MIGRATION: 'true'
            SSL_MODE: 'off'
        networks:
            - db_net
            - redis_net
        command: ['su', 'webuser', '-c', 'php artisan schedule:work']

    # Database
    ls_dev_db:
        image: mysql:latest
        container_name: ls_dev_db
        restart: unless-stopped
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            ON_CREATE_DB: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - db_net

    # Redis
    ls_dev_redis:
        image: redis:alpine
        container_name: ls_dev_redis
        hostname: laravel_app_x
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - redis_net

    # MailHog Server
    ls_dev_mail_hog:
        image: mailhog/mailhog:latest
        container_name: ls_dev_mail_hog
        restart: unless-stopped
        ports:
            - 10001:1025
            - 10002:8025

networks:
    db_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.20.0.0/16

    redis_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.50.0.0/16
